services:
  nextjs:
    build: ./frontend
    ports:
      - "3000:3000"
  express:
    build: ./backend
    ports:
      - "3001:3001"

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASWORD: root
      MYSQL_DATABASE: bank
    ports:
      #den kommer köra 3307 på min dator men 3306 inuti containern, se till att backend är kopplad till 3307
      - "3307:3306"
