jobs:
  deployment:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 60 # Increase the timeout to 60 minutes
    steps:
      - name: Check out Repo
        uses: actions/checkout@v4

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "."
          target: "/home/ubuntu/docker-github-actions"

      - name: Free up disk space
        run: |
          docker system prune -f
          docker volume prune -f

      - name: Run Docker on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/docker-github-actions
            sudo docker system prune -f
            sudo docker-compose down
            sudo docker-compose up --build -d
